package com.stockpilot.security;
import com.stockpilot.common.exception.BusinessException;import com.stockpilot.security.application.*;import com.stockpilot.security.audit.AuditService;import com.stockpilot.security.auth.JwtService;import com.stockpilot.security.config.SecurityProperties;import com.stockpilot.security.domain.*;import com.stockpilot.security.infrastructure.mapper.*;import com.stockpilot.security.request.SecurityRequests;import org.junit.jupiter.api.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class AuthenticationApplicationServiceTest {
 private UserMapper users;private AuditLogMapper logs;private BCryptPasswordEncoder encoder;private AuthenticationApplicationService service;
 @BeforeEach void setUp(){users=mock(UserMapper.class);logs=mock(AuditLogMapper.class);encoder=new BCryptPasswordEncoder(4);SecurityProperties p=new SecurityProperties("01234567890123456789012345678901",60,"","");service=new AuthenticationApplicationService(users,mock(RoleMapper.class),encoder,new JwtService(p),new AuditService(logs),p);}
 @Test void correctLoginReturnsTokenAndAudit(){when(users.findByUsername("alice")).thenReturn(user(SecurityStatus.ENABLED,"correct-password"));var token=service.login(new SecurityRequests.Login("alice","correct-password"));assertEquals("Bearer",token.tokenType());assertNotNull(token.accessToken());verify(logs).insert(argThat(e->"LOGIN".equals(e.getActionType())&&"SUCCESS".equals(e.getResult())&&!String.valueOf(e.getSummary()).contains("correct-password")));}
 @Test void wrongPasswordAndUnknownUserUseSafeFailure(){when(users.findByUsername("alice")).thenReturn(user(SecurityStatus.ENABLED,"correct-password"));BusinessException wrong=assertThrows(BusinessException.class,()->service.login(new SecurityRequests.Login("alice","wrong-password")));assertEquals("AUTH_401",wrong.getErrorCode().code());BusinessException missing=assertThrows(BusinessException.class,()->service.login(new SecurityRequests.Login("missing","whateverxx")));assertEquals("AUTH_401",missing.getErrorCode().code());verify(logs,times(2)).insert(argThat(e->"FAILURE".equals(e.getResult())&&!String.valueOf(e.getSummary()).contains("wrong-password")&&!String.valueOf(e.getSummary()).contains("whateverxx")));}
 @Test void disabledUserUsesSamePublicErrorAsOtherCredentialFailures(){when(users.findByUsername("alice")).thenReturn(user(SecurityStatus.DISABLED,"correct-password"));BusinessException ex=assertThrows(BusinessException.class,()->service.login(new SecurityRequests.Login("alice","correct-password")));assertEquals("AUTH_401",ex.getErrorCode().code());assertEquals("用户名或密码错误",ex.getMessage());verify(logs).insert(argThat(e->"用户已停用".equals(e.getSummary())));}
 @Test void createdUserStoresBcryptNotPlainPasswordAndCreatesSafeAudit(){when(users.insert(any())).thenAnswer(i->{UserEntity e=i.getArgument(0);e.setId(9L);e.setVersion(0);return 1;});when(users.findRoleIds(9L)).thenReturn(List.of());SecurityManagementApplicationService management=new SecurityManagementApplicationService(users,mock(RoleMapper.class),mock(PermissionMapper.class),logs,encoder,new AuditService(logs));management.createUser(new SecurityRequests.CreateUser("alice","Secret123!","Alice"));verify(users).insert(argThat(e->!"Secret123!".equals(e.getPasswordHash())&&encoder.matches("Secret123!",e.getPasswordHash())));verify(logs).insert(argThat(e->!String.valueOf(e.getSummary()).contains("Secret123!")));}
 private UserEntity user(SecurityStatus status,String raw){UserEntity u=new UserEntity();u.setId(1L);u.setUsername("alice");u.setDisplayName("Alice");u.setStatus(status);u.setPasswordHash(encoder.encode(raw));u.setVersion(0);return u;}
}
