package com.stockpilot.security.application;
import com.stockpilot.common.exception.BusinessException; import com.stockpilot.security.api.SecurityErrorCode; import com.stockpilot.security.audit.AuditService; import com.stockpilot.security.auth.JwtService; import com.stockpilot.security.config.SecurityProperties; import com.stockpilot.security.domain.*; import com.stockpilot.security.infrastructure.mapper.*; import com.stockpilot.security.request.SecurityRequests; import com.stockpilot.security.vo.SecurityVO;
import org.springframework.boot.ApplicationArguments; import org.springframework.boot.ApplicationRunner; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.util.StringUtils; import java.time.Duration;
@Service public class AuthenticationApplicationService implements ApplicationRunner {
 private final UserMapper users;private final RoleMapper roles;private final PasswordEncoder passwords;private final JwtService jwt;private final AuditService audit;private final SecurityProperties properties;private final String dummyPasswordHash;
 public AuthenticationApplicationService(UserMapper u,RoleMapper r,PasswordEncoder p,JwtService j,AuditService a,SecurityProperties sp){users=u;roles=r;passwords=p;jwt=j;audit=a;properties=sp;dummyPasswordHash=p.encode("stockpilot-login-timing-placeholder");}
 public SecurityVO.Token login(SecurityRequests.Login r){String username=r.username().trim();UserEntity u=users.findByUsername(username);if(u==null){passwords.matches(r.password(),dummyPasswordHash);audit.recordLogin(null,username,"FAILURE","用户不存在");throw new BusinessException(SecurityErrorCode.INVALID_CREDENTIALS);}boolean passwordMatches=passwords.matches(r.password(),u.getPasswordHash());if(u.getStatus()!=SecurityStatus.ENABLED){audit.recordLogin(u.getId(),u.getUsername(),"FAILURE","用户已停用");throw new BusinessException(SecurityErrorCode.INVALID_CREDENTIALS);}if(!passwordMatches){audit.recordLogin(u.getId(),u.getUsername(),"FAILURE","凭据错误");throw new BusinessException(SecurityErrorCode.INVALID_CREDENTIALS);}String token=jwt.issue(u.getId(),u.getUsername());JwtService.Claims c=jwt.verify(token);audit.recordLogin(u.getId(),u.getUsername(),"SUCCESS","登录成功");return new SecurityVO.Token(token,"Bearer",c.expiresAt());}
 public void run(ApplicationArguments args){if(!StringUtils.hasText(properties.bootstrapAdminUsername())&&!StringUtils.hasText(properties.bootstrapAdminPassword()))return;if(!StringUtils.hasText(properties.bootstrapAdminUsername())||!StringUtils.hasText(properties.bootstrapAdminPassword())||properties.bootstrapAdminPassword().length()<8)throw new IllegalStateException("Bootstrap admin credentials must both be set and password must have at least 8 characters");if(users.findByUsername(properties.bootstrapAdminUsername())!=null)return;UserEntity u=new UserEntity();u.setUsername(properties.bootstrapAdminUsername().trim());u.setDisplayName("系统管理员");u.setPasswordHash(passwords.encode(properties.bootstrapAdminPassword()));u.setStatus(SecurityStatus.ENABLED);users.insert(u);RoleEntity admin=roles.selectOne(new com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<RoleEntity>().eq(RoleEntity::getCode,"SYSTEM_ADMIN"));if(admin==null)throw new IllegalStateException("SYSTEM_ADMIN role missing");users.insertRoles(u.getId(),java.util.List.of(admin.getId()));audit.recordLogin(u.getId(),u.getUsername(),"SUCCESS","引导管理员已创建");}
}
